name: ColorAnvil
author: GKFire
api-version: 1.13
version: 1.5.2
main: io.github.gkfire.coloranvil.Main
commands:
  ca:
    description: ColorAnvil Main Command.
    aliases: ca
    usage: /ca <argument>